version: "3.8"

services:
  store-service:
    image: thappatan/store-service:0.0.1
    container_name: store-service
    build:
      context: store-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - store-database
    restart: always
    environment: 
      - TEST_MODE=true
      - BANK_GATEWAY=payment-gateway
      - SHIPPING_GATEWAY=shipping-gateway
      - DBCONNECTION=root:password@(store-database:3306)/storeDB

  shipping-gateway:
    image: andyrbell/mountebank:2.3.2
    container_name: shipping-gateway
    volumes:
      - ./shipping-gateway/imposters.json:/imposters/imposters.json
    restart: always
    command:
      [
        'mb',
        'start',
        '--configfile',
        '/imposters/imposters.json',
        '--allowInjection',
      ]

  payment-gateway:
    image: andyrbell/mountebank:2.3.2
    container_name: payment-gateway
    volumes:
      - ./payment-gateway/imposters.json:/imposters/imposters.json
    restart: always
    command:
      [
        'mb',
        'start',
        '--configfile',
        '/imposters/imposters.json',
        '--allowInjection',
      ]

  store-database:
    image: mysql:8.0.22
    container_name: store-database
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=storeDB
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    ports:
      - '3306:3306'
  
  store-nginx:
    image: nginx:1.19.3-alpine
    container_name: store-nginx
    restart: always
    volumes:
        - ./html:/etc/nginx/html:ro
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - store-service
    ports:
      - "80:80"
    
  
